version: '3'

services:
  php:
    container_name: jobsity-php
    build: ./docker/php
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql

  nginx:
    container_name: jobsity_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: jobsity-mysql
    image: mariadb:10.8
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=r00tp455
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
